buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.testcontainers:postgresql:1.20.1"
    }
}

import org.testcontainers.containers.PostgreSQLContainer
import org.testcontainers.utility.DockerImageName

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.13'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.freefair.lombok' version '8.4'
    id 'nu.studer.jooq' version '9.0'
}

apply from: 'version.gradle'

group = 'org.senla'
version = '0.0.1-SNAPSHOT'
description = 'error-free-text'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

configurations {
    liquibaseRuntime
}

ext {
    jooq = '3.19.23'
    liquibase = '4.31.1'
    mapstruct = '1.6.3'
    lombok = '1.18.30'
    slf4j = '2.0.16'
    postgres = '42.7.8'
    testcontainers = '1.20.1'

    jooqConfig = [
            edition    : nu.studer.gradle.jooq.JooqEdition.OSS,
            packageName: 'org.senla.jooq.generated',
            outputDir  : 'build/generated-src/jooq/main',
            changelog  : 'db/changelog/db.changelog-master.xml',
            inputSchema: 'public'
    ]
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-validation"

    implementation "org.springframework.boot:spring-boot-starter-jooq"
    implementation "org.jooq:jooq:${jooq}"
    implementation "org.postgresql:postgresql:${postgres}"
    implementation "org.liquibase:liquibase-core:${liquibase}"

    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstruct}"
    implementation "org.mapstruct:mapstruct:${mapstruct}"

    compileOnly "org.projectlombok:lombok:${lombok}"
    annotationProcessor "org.projectlombok:lombok:${lombok}"

    testCompileOnly "org.projectlombok:lombok:${lombok}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombok}"

    testImplementation "org.testcontainers:junit-jupiter:${testcontainers}"
    testImplementation "org.testcontainers:postgresql:${testcontainers}"
    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation "org.springframework.boot:spring-boot-starter-test"

    jooqGenerator "org.postgresql:postgresql:${postgres}"
    jooqGenerator "org.slf4j:slf4j-simple:${slf4j}"

    liquibaseRuntime "org.liquibase:liquibase-core:${liquibase}"
    liquibaseRuntime "org.postgresql:postgresql:${postgres}"
    liquibaseRuntime "org.slf4j:slf4j-simple:${slf4j}"
}

test {
    useJUnitPlatform()
}

def getJooqPostgres = {
    new PostgreSQLContainer(DockerImageName.parse("postgres:16.2").asCompatibleSubstituteFor("postgres"))
            .withDatabaseName("jooq_codegen")
            .withUsername("postgres")
            .withPassword("postgres")
            .tap { start() }
}.memoize()

tasks.register('migrateJooqDb', JavaExec) {
    mainClass = 'liquibase.integration.commandline.Main'

    doFirst {
        def pg = getJooqPostgres()

        classpath = files(
                configurations.liquibaseRuntime,
                sourceSets.main.resources.srcDirs
        )

        args = [
                "--changeLogFile=${jooqConfig.changelog}",
                "--url=${pg.getJdbcUrl()}",
                "--username=${pg.getUsername()}",
                "--password=${pg.getPassword()}",
                "--driver=org.postgresql.Driver",
                "update"
        ]
    }
}

tasks.register('stopPostgreSQLContainer') {
    doLast {
        try {
            def pg = getJooqPostgres()
            if (pg != null && pg.isRunning()) {
                pg.stop()
                pg.close()
            }
        } catch (Exception ignored) {
        }
    }
}

tasks.withType(nu.studer.gradle.jooq.JooqGenerate).configureEach {
    launcher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

jooq {
    version = jooq
    edition = nu.studer.gradle.jooq.JooqEdition.OSS

    configurations {
        main {
            generateSchemaSourceOnCompilation = false

            generationTool {
                logging = 'INFO'

                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = "${-> getJooqPostgres().getJdbcUrl()}"
                    user = "${-> getJooqPostgres().getUsername()}"
                    password = "${-> getJooqPostgres().getPassword()}"
                }

                generator {
                    name = 'org.jooq.codegen.JavaGenerator'

                    database {
                        name = 'org.jooq.meta.postgres.PostgresDatabase'
                        inputSchema = jooqConfig.inputSchema
                        excludes = 'databasechangelog|databasechangeloglock'
                    }

                    target {
                        packageName = jooqConfig.packageName
                        directory = jooqConfig.outputDir
                    }
                }
            }
        }
    }
}

tasks.named('generateJooq', nu.studer.gradle.jooq.JooqGenerate) {
    dependsOn tasks.named('migrateJooqDb')
    finalizedBy tasks.named('stopPostgreSQLContainer')
}

tasks.named('compileJava') {
    dependsOn tasks.named('generateJooq')
}

sourceSets {
    main {
        java {
            srcDir jooqConfig.outputDir
        }
    }
}