server:
  port: 8080

spring:
  application:
    name: error-free-txt

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      pool-name: booking-pool

  jooq:
    sql-dialect: POSTGRES

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

content-size: 100

async-processor:
  pool-size: 5
  queue-size: 10

scheduler:
  interval-ms: 10000
  batch-size: 10
  pool-size: 1
  enabled: true

rest-client:
  yandex-url: https://speller.yandex.net/services/spellservice.json/checkTexts
  http:
    connect-timeout-ms: 3000
    socket-timeout-ms: 5000
    connection-request-timeout-ms: 3000
    connection-ttl-seconds: 30
    idle-evict-seconds: 30
    max-total: 100
    max-per-route: 20

logging:
  level:
    org.senla.errorfreetext: TRACE
    org.jooq.tools.LoggerListener: DEBUG